---
- name: Add Elastic's GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add ElasticSearch yum repo
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Open 9200/tcp in firewalld
  firewalld:
    port: 9200/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Install ElasticSearch 
  yum:
    name: "elasticsearch-{{ es_version }}.x86_64"
    state: present

- name: Set ElasticSearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: Restart Elasticsearch

- name: Set jvm options
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options

- name: Create cert folder
  file:
    path: /etc/elasticsearch/certs
    state: directory
    group: elasticsearch

- name: enable Elasticsearch and start the service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started

- name: Install pyhton-pip for the expect command
  yum:
    name: python-pip
    state: present

- name: Install pexpect
  pip:
    name: pexpect

- name: See if elastic-passwords.txt already exists
  stat:
    path: /root/elastic-passwords.txt
  register: elastic_passwords_file

- name: Generate random Elastic passwords
  expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto
    responses:
      (?i)N]: y
    creates: /root/elastic-passwords.txt
  register: elastic_passwords_out

- name: Copy generated passwords to file
  copy:
    content: "{{ elastic_passwords_out }}"
    dest: "/root/elastic-passwords.txt"
  delegate_to: localhost
  when: not elastic_passwords_file.stat.exists